config/routes.rb
WhereHaveYouBeen::Application.routes.draw do
  resources :comments

  get "experiments_controller/index"

  resources :trips

  devise_for :users do
  end

  root :to => 'home#index'
  match '/trips' => 'trips#index', as: :user_root

  match '/experimental' => 'experiments#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :body, :presence => true
  
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :trip

  validates :name, :trip, presence: true

  attr_accessible :name
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user

  validates :name, :presence => true
  validates :user, :presence => true
  validates :begun_on, :presence => true, :if => Proc.new {|trip| trip.ended_on.present?}
  validates :ended_on, :presence => true, :if => Proc.new {|trip| trip.begun_on.present?}

  attr_accessible :name, :places_attributes, :begun_on, :ended_on

  has_many :places, dependent: :destroy, :inverse_of => :trip

  accepts_nested_attributes_for :places, :reject_if => :all_blank

  scope :desc, order('created_at DESC')

  def as_json(opts={})
    super(opts.merge(:include => :places))
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  before_save :ensure_authentication_token

  has_many :trips, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: {errors: @comment.errors}, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: {errors: @comment.errors}, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :ok }
    end
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :find_trip_if_authorized, only: [:edit,:update,:destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.desc.all
    @latest_trip = @trips.first

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = current_user.trips.build
    5.times {@trip.places.build}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    (5-@trip.places.count).times {@trip.places.build}
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = current_user.trips.build(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :ok }
    end
  end

  private

  def find_trip_if_authorized
    @trip = current_user.trips.find_by_id(params[:id])
    if @trip.nil?
      flash[:alert] = "You don't have permissions for this operation"
      redirect_to trips_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    t = content_for :title
    t.blank? ? 'Where have you been?' : t
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper

  def geocoded(trip)
    @geocoded ||= trip.places.inject([]) do |array,place|
      array << Gmaps4rails.geocode(place.name).first
    end
  end

  def polylines(trip)
    polylines = geocoded(trip).map do |geo|
      {lng: geo[:lng], lat: geo[:lat]}
    end
    [polylines]  # the API expects and array of polylines
  end
end

app/views/comments/_form.html.haml
= simple_form_for(@comment) do |f|
  = f.error_notification

  .inputs
    = f.input :body

  .actions
    = f.button :submit

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th Body
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.body
      %td= link_to 'Show', comment
      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @comment.body

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path

app/views/experiments/index.html.haml
%h2 Experiments

- city = 'San Francisco, CA'
- gmap = Gmaps4rails.geocode(city).first


= gmaps({markers: {data: [gmap].to_json}, map_options: {auto_zoom: false, zoom: 10}})

-#This should go at the end of the application layout for best page loading experience
= yield :scripts

app/views/home/index.html.haml
= content_for :title, 'Where have you been?'

.row
  .span-1
  .span-3
    %p
      %b Trip:
      Peru
    %p
      %b City/Place:
      Machu Picchu
    %p.small
      Andes in the Urubamba valley along the train tracks on the way up to Machu Picchu.

  .span-16.centered
    = image_tag 'home_photo.jpg'

  .span-4.last
    - unless user_signed_in?
      = button_to 'Sign Up', new_user_registration_path, :method => :get
      %br
      Got an account?
      = link_to 'Sign In', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "application"

    %title
      Where Have You Been?

    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .row
      .span-24.spacer

    .row
      .span-6
        - flash.each do |key,val|
          - unless val.blank?
            %p{class: key}
              = val
      .span-12
        .title
          %h1
            = title

      .span-2
      .span-4.last
        - if user_signed_in?
          = link_to "Sign Out", destroy_user_session_path
        - else
          = link_to "Sign In", new_user_session_path
          %br
          No account?
          = link_to "Sign Up", new_user_registration_path
          
    .row
      .span-24.spacer
    .row
      .span-24.spacer

    .column
      = yield

app/views/trips/_form.html.haml
= simple_form_for @trip do |f|
  = f.error_notification

  = f.input :name
  = f.input :begun_on, :label => 'from', :include_blank => true
  = f.input :ended_on, :label => 'to', :include_blank => true

  %ul
  = f.simple_fields_for :places do |places_form|
    %li
      = places_form.input :name, :label => "Place/City"

  = f.button :submit, 'Save'

app/views/trips/_show.html.haml
%h2= trip.name

- if trip.begun_on.present?
  %h3
    = trip.begun_on
    to
    = trip.ended_on

%h3 Places visited

%ul
  - trip.places.each do |place|
    %li
      = place.name

= gmaps(markers:   {data: geocoded(trip).to_json},
        polylines: {data: polylines(trip).to_json})

-#This should go at the end of the application layout for best page loading experience
= yield :scripts

app/views/trips/edit.html.haml
%h2 Editing trip

= render 'form'

= link_to 'Show', @trip
\|
= link_to 'Back', trips_path

app/views/trips/index.html.haml
= render 'show', :trip => @latest_trip if @latest_trip.present?

%h2 Other Trips

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @trips.each do |trip|
    %tr
      %td= trip.name
      %td= link_to 'Show', trip
      %td= link_to 'Edit', edit_trip_path(trip)
      %td= link_to 'Destroy', trip, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Trip', new_trip_path

app/views/trips/new.html.haml
%h2 New trip

= render 'form'

= link_to 'Back', trips_path

app/views/trips/show.html.haml
= render 'show', :trip => @trip

= link_to 'Edit', edit_trip_path(@trip)
\|
= link_to 'Back', trips_path